/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedStudentsIndexRouteImport } from './routes/_protected/students/index'
import { Route as ProtectedAcademicsIndexRouteImport } from './routes/_protected/academics/index'
import { Route as ProtectedStudentsGradeIdRouteImport } from './routes/_protected/students/$gradeId'
import { Route as ProtectedStudentsGraduatesIndexRouteImport } from './routes/_protected/students/graduates/index'
import { Route as ProtectedAcademicsAssessmentsIndexRouteImport } from './routes/_protected/academics/assessments/index'
import { Route as ProtectedAcademicsAssessmentsAssessmentIdIndexRouteImport } from './routes/_protected/academics/assessments/$assessmentId/index'
import { Route as ProtectedAcademicsAssessmentsUpsertCreateRouteImport } from './routes/_protected/academics/assessments/upsert/create'
import { Route as ProtectedAcademicsAssessmentsTempAssessmentIdRouteImport } from './routes/_protected/academics/assessments/temp.$assessmentId'
import { Route as ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRouteImport } from './routes/_protected/academics/assessments/upsert/edit.$assessmentId'
import { Route as ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRouteImport } from './routes/_protected/academics/assessments/$assessmentId/results/$gradeId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedStudentsIndexRoute = ProtectedStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAcademicsIndexRoute = ProtectedAcademicsIndexRouteImport.update({
  id: '/academics/',
  path: '/academics/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStudentsGradeIdRoute =
  ProtectedStudentsGradeIdRouteImport.update({
    id: '/students/$gradeId',
    path: '/students/$gradeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentsGraduatesIndexRoute =
  ProtectedStudentsGraduatesIndexRouteImport.update({
    id: '/students/graduates/',
    path: '/students/graduates/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsIndexRoute =
  ProtectedAcademicsAssessmentsIndexRouteImport.update({
    id: '/academics/assessments/',
    path: '/academics/assessments/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsAssessmentIdIndexRoute =
  ProtectedAcademicsAssessmentsAssessmentIdIndexRouteImport.update({
    id: '/academics/assessments/$assessmentId/',
    path: '/academics/assessments/$assessmentId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsUpsertCreateRoute =
  ProtectedAcademicsAssessmentsUpsertCreateRouteImport.update({
    id: '/academics/assessments/upsert/create',
    path: '/academics/assessments/upsert/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsTempAssessmentIdRoute =
  ProtectedAcademicsAssessmentsTempAssessmentIdRouteImport.update({
    id: '/academics/assessments/temp/$assessmentId',
    path: '/academics/assessments/temp/$assessmentId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute =
  ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRouteImport.update({
    id: '/academics/assessments/upsert/edit/$assessmentId',
    path: '/academics/assessments/upsert/edit/$assessmentId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute =
  ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRouteImport.update({
    id: '/academics/assessments/$assessmentId/results/$gradeId',
    path: '/academics/assessments/$assessmentId/results/$gradeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof PublicLoginRoute
  '/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/academics/': typeof ProtectedAcademicsIndexRoute
  '/students/': typeof ProtectedStudentsIndexRoute
  '/academics/assessments/': typeof ProtectedAcademicsAssessmentsIndexRoute
  '/students/graduates/': typeof ProtectedStudentsGraduatesIndexRoute
  '/academics/assessments/temp/$assessmentId': typeof ProtectedAcademicsAssessmentsTempAssessmentIdRoute
  '/academics/assessments/upsert/create': typeof ProtectedAcademicsAssessmentsUpsertCreateRoute
  '/academics/assessments/$assessmentId/': typeof ProtectedAcademicsAssessmentsAssessmentIdIndexRoute
  '/academics/assessments/$assessmentId/results/$gradeId': typeof ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute
  '/academics/assessments/upsert/edit/$assessmentId': typeof ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof PublicLoginRoute
  '/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/academics': typeof ProtectedAcademicsIndexRoute
  '/students': typeof ProtectedStudentsIndexRoute
  '/academics/assessments': typeof ProtectedAcademicsAssessmentsIndexRoute
  '/students/graduates': typeof ProtectedStudentsGraduatesIndexRoute
  '/academics/assessments/temp/$assessmentId': typeof ProtectedAcademicsAssessmentsTempAssessmentIdRoute
  '/academics/assessments/upsert/create': typeof ProtectedAcademicsAssessmentsUpsertCreateRoute
  '/academics/assessments/$assessmentId': typeof ProtectedAcademicsAssessmentsAssessmentIdIndexRoute
  '/academics/assessments/$assessmentId/results/$gradeId': typeof ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute
  '/academics/assessments/upsert/edit/$assessmentId': typeof ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/_protected/academics/': typeof ProtectedAcademicsIndexRoute
  '/_protected/students/': typeof ProtectedStudentsIndexRoute
  '/_protected/academics/assessments/': typeof ProtectedAcademicsAssessmentsIndexRoute
  '/_protected/students/graduates/': typeof ProtectedStudentsGraduatesIndexRoute
  '/_protected/academics/assessments/temp/$assessmentId': typeof ProtectedAcademicsAssessmentsTempAssessmentIdRoute
  '/_protected/academics/assessments/upsert/create': typeof ProtectedAcademicsAssessmentsUpsertCreateRoute
  '/_protected/academics/assessments/$assessmentId/': typeof ProtectedAcademicsAssessmentsAssessmentIdIndexRoute
  '/_protected/academics/assessments/$assessmentId/results/$gradeId': typeof ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute
  '/_protected/academics/assessments/upsert/edit/$assessmentId': typeof ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/students/$gradeId'
    | '/academics/'
    | '/students/'
    | '/academics/assessments/'
    | '/students/graduates/'
    | '/academics/assessments/temp/$assessmentId'
    | '/academics/assessments/upsert/create'
    | '/academics/assessments/$assessmentId/'
    | '/academics/assessments/$assessmentId/results/$gradeId'
    | '/academics/assessments/upsert/edit/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/students/$gradeId'
    | '/academics'
    | '/students'
    | '/academics/assessments'
    | '/students/graduates'
    | '/academics/assessments/temp/$assessmentId'
    | '/academics/assessments/upsert/create'
    | '/academics/assessments/$assessmentId'
    | '/academics/assessments/$assessmentId/results/$gradeId'
    | '/academics/assessments/upsert/edit/$assessmentId'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/login'
    | '/_protected/'
    | '/_protected/students/$gradeId'
    | '/_protected/academics/'
    | '/_protected/students/'
    | '/_protected/academics/assessments/'
    | '/_protected/students/graduates/'
    | '/_protected/academics/assessments/temp/$assessmentId'
    | '/_protected/academics/assessments/upsert/create'
    | '/_protected/academics/assessments/$assessmentId/'
    | '/_protected/academics/assessments/$assessmentId/results/$gradeId'
    | '/_protected/academics/assessments/upsert/edit/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/students/': {
      id: '/_protected/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof ProtectedStudentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/': {
      id: '/_protected/academics/'
      path: '/academics'
      fullPath: '/academics/'
      preLoaderRoute: typeof ProtectedAcademicsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$gradeId': {
      id: '/_protected/students/$gradeId'
      path: '/students/$gradeId'
      fullPath: '/students/$gradeId'
      preLoaderRoute: typeof ProtectedStudentsGradeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/graduates/': {
      id: '/_protected/students/graduates/'
      path: '/students/graduates'
      fullPath: '/students/graduates/'
      preLoaderRoute: typeof ProtectedStudentsGraduatesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/': {
      id: '/_protected/academics/assessments/'
      path: '/academics/assessments'
      fullPath: '/academics/assessments/'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/$assessmentId/': {
      id: '/_protected/academics/assessments/$assessmentId/'
      path: '/academics/assessments/$assessmentId'
      fullPath: '/academics/assessments/$assessmentId/'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsAssessmentIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/upsert/create': {
      id: '/_protected/academics/assessments/upsert/create'
      path: '/academics/assessments/upsert/create'
      fullPath: '/academics/assessments/upsert/create'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsUpsertCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/temp/$assessmentId': {
      id: '/_protected/academics/assessments/temp/$assessmentId'
      path: '/academics/assessments/temp/$assessmentId'
      fullPath: '/academics/assessments/temp/$assessmentId'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsTempAssessmentIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/upsert/edit/$assessmentId': {
      id: '/_protected/academics/assessments/upsert/edit/$assessmentId'
      path: '/academics/assessments/upsert/edit/$assessmentId'
      fullPath: '/academics/assessments/upsert/edit/$assessmentId'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/academics/assessments/$assessmentId/results/$gradeId': {
      id: '/_protected/academics/assessments/$assessmentId/results/$gradeId'
      path: '/academics/assessments/$assessmentId/results/$gradeId'
      fullPath: '/academics/assessments/$assessmentId/results/$gradeId'
      preLoaderRoute: typeof ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedStudentsGradeIdRoute: typeof ProtectedStudentsGradeIdRoute
  ProtectedAcademicsIndexRoute: typeof ProtectedAcademicsIndexRoute
  ProtectedStudentsIndexRoute: typeof ProtectedStudentsIndexRoute
  ProtectedAcademicsAssessmentsIndexRoute: typeof ProtectedAcademicsAssessmentsIndexRoute
  ProtectedStudentsGraduatesIndexRoute: typeof ProtectedStudentsGraduatesIndexRoute
  ProtectedAcademicsAssessmentsTempAssessmentIdRoute: typeof ProtectedAcademicsAssessmentsTempAssessmentIdRoute
  ProtectedAcademicsAssessmentsUpsertCreateRoute: typeof ProtectedAcademicsAssessmentsUpsertCreateRoute
  ProtectedAcademicsAssessmentsAssessmentIdIndexRoute: typeof ProtectedAcademicsAssessmentsAssessmentIdIndexRoute
  ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute: typeof ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute
  ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute: typeof ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedStudentsGradeIdRoute: ProtectedStudentsGradeIdRoute,
  ProtectedAcademicsIndexRoute: ProtectedAcademicsIndexRoute,
  ProtectedStudentsIndexRoute: ProtectedStudentsIndexRoute,
  ProtectedAcademicsAssessmentsIndexRoute:
    ProtectedAcademicsAssessmentsIndexRoute,
  ProtectedStudentsGraduatesIndexRoute: ProtectedStudentsGraduatesIndexRoute,
  ProtectedAcademicsAssessmentsTempAssessmentIdRoute:
    ProtectedAcademicsAssessmentsTempAssessmentIdRoute,
  ProtectedAcademicsAssessmentsUpsertCreateRoute:
    ProtectedAcademicsAssessmentsUpsertCreateRoute,
  ProtectedAcademicsAssessmentsAssessmentIdIndexRoute:
    ProtectedAcademicsAssessmentsAssessmentIdIndexRoute,
  ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute:
    ProtectedAcademicsAssessmentsAssessmentIdResultsGradeIdRoute,
  ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute:
    ProtectedAcademicsAssessmentsUpsertEditAssessmentIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
