/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedStudentsIndexRouteImport } from './routes/_protected/students/index'
import { Route as ProtectedStudentsGradeIdRouteImport } from './routes/_protected/students/$gradeId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedStudentsIndexRoute = ProtectedStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStudentsGradeIdRoute =
  ProtectedStudentsGradeIdRouteImport.update({
    id: '/students/$gradeId',
    path: '/students/$gradeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof PublicLoginRoute
  '/': typeof ProtectedIndexRoute
  '/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/students': typeof ProtectedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/': typeof ProtectedIndexRoute
  '/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/students': typeof ProtectedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/students/$gradeId': typeof ProtectedStudentsGradeIdRoute
  '/_protected/students/': typeof ProtectedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/students/$gradeId' | '/students'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/students/$gradeId' | '/students'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/login'
    | '/_protected/'
    | '/_protected/students/$gradeId'
    | '/_protected/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/students/': {
      id: '/_protected/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof ProtectedStudentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/students/$gradeId': {
      id: '/_protected/students/$gradeId'
      path: '/students/$gradeId'
      fullPath: '/students/$gradeId'
      preLoaderRoute: typeof ProtectedStudentsGradeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedStudentsGradeIdRoute: typeof ProtectedStudentsGradeIdRoute
  ProtectedStudentsIndexRoute: typeof ProtectedStudentsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedStudentsGradeIdRoute: ProtectedStudentsGradeIdRoute,
  ProtectedStudentsIndexRoute: ProtectedStudentsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
